config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :show]
  get "/welcome", to: "layouts#index"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  root 'layouts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resources :master_goals
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :master_goal
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def current_user
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end

  def authorized
    redirect_to login_path unless logged_in?
  end
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
      redirect_to @user
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorized, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      @user.save
      redirect_to @user
    else
      redirect :new
    end
  end

  def show
     @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Golo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= yield %>

  <br>

  <% if logged_in? %>
    <%= button_to "Logout", sessions_path, method: :delete %>
  <% else %>
    <%= button_to "Login Page", login_path, method: :get %>
  <% end %>
  </body>
</html>

app/views/layouts/index.html.erb
<H3>hello</H3>

<form class="button_to" method="get" action="/signup"><input type="submit" value="Sign Up" /></form>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username, placeholder: "Username" %>
  <%= f.label :password %>
  <%= f.password_field :password, placeholder: "Password" %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1>This is profile "<%= @user.username %>"</h2>

  <% if current_user == @user %>
    <h3>This is your page.</h3>

    <h2>Master goal:</h2>
    <%= form_with(model: [ @user, @master_goal = @user.build_master_goal ], local: true) do |form| %>
      <p>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
      </p>
      <p>
        <%= form.label :specific %><br>
        <%= form.text_area :specific %>
      </p>
      <p>
        <%= form.label :measurable %><br>
        <%= form.text_area :measurable %>
      </p>
      <p>
        <%= form.label :action %><br>
        <%= form.text_area :action %>
      </p>
      <p>
        <%= form.label :realistic %><br>
        <%= form.text_area :realistic %>
      </p>
      <p>
        <%= form.label :time %><br>
        <%= form.text_area :time %>
      </p>
      <p>
        <%= form.label :why %><br>
        <%= form.text_area :why %>
      </p>
      <p>
        <%= form.submit %>
      </p>
    <% end %>

  <% else %>
    <h3>Not your page!!!</h3>
  <% end %>